modLoader="javafml"
loaderVersion="[${loader_version},)"
license="All rights reserved"
issueTrackerURL="https://github.com/MeinKraft/Crimson-Juices/issues" #optional

[[mods]]
modId="crimsonjuices"
version="${version}"
displayName="Crimson Juices"
displayURL="https://www.curseforge.com/minecraft/mc-mods/crimson-juices"
authors="§4Crimson_Fluff"
logoFile="logo.png" #optional
credits="\n§bRaziel23x§r for casually giving me the push I needed !\n§bTechnovision§r for his awesome modding YouTube series\n§bTurtyWurty§r for his awesome modding YouTube series" #optional
description=''' "Anything can be juiced with a big enough squeezer" '''

[[dependencies.crimsonjuices]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    side="BOTH"
[[dependencies.crimsonjuices]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    side="BOTH"
